#!/bin/sh
set -eu

# One switch controls both the Pulp API authenticators and the runtime UI.
# Supported modes:
#   sso   - Entra login and Django sessions only (default)
#   basic - Pulp's traditional username/password login plus sessions
case "${PULP_AUTH_MODE:-sso}" in
  sso)
    external_login_uri='/login/azuread-tenant-oauth2/'
    ;;
  basic)
    external_login_uri=''
    ;;
  *)
    echo "Unsupported PULP_AUTH_MODE=${PULP_AUTH_MODE}; expected sso or basic" >&2
    exit 64
    ;;
esac

settings_file=/etc/pulp/settings.py
sed -i '/^# BEGIN AXALON AUTH MODE$/,/^# END AXALON AUTH MODE$/d' "$settings_file"

if [ "${PULP_AUTH_MODE:-sso}" = sso ]; then
  cat >> "$settings_file" <<'PYTHON'
# BEGIN AXALON AUTH MODE
# Generated by axalon-auth-entrypoint.sh. The local marker disables
# Dynaconf's recursive merge for this dictionary so BasicAuthentication is
# removed instead of retained from Pulpcore defaults.
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.SessionAuthentication",
    ],
    "URL_FIELD_NAME": "pulp_href",
    "DEFAULT_FILTER_BACKENDS": ["pulpcore.filters.PulpFilterBackend"],
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.LimitOffsetPagination",
    "PAGE_SIZE": 100,
    "DEFAULT_PERMISSION_CLASSES": ["pulpcore.app.access_policy.AccessPolicyFromDB"],
    "UPLOADED_FILES_USE_URL": False,
    "DEFAULT_VERSIONING_CLASS": "rest_framework.versioning.URLPathVersioning",
    "DEFAULT_SCHEMA_CLASS": "pulpcore.openapi.PulpAutoSchema",
    "dynaconf_merge": False,
}
# END AXALON AUTH MODE
PYTHON
fi

cat > /var/lib/operator/static/pulp_ui/pulp-ui-config.json <<EOF
{
  "API_BASE_PATH": "/pulp/api/v3/",
  "UI_BASE_PATH": "/ui/",
  "UI_EXTERNAL_LOGIN_URI": "${external_login_uri}",
  "EXTRA_VERSION": ""
}
EOF
chown 1001:1001 /var/lib/operator/static/pulp_ui/pulp-ui-config.json

exec /init
