location = /static/pulp_ui/index.html {
    root /var/lib/operator/;
    add_header Cache-Control "no-store, no-cache, must-revalidate, max-age=0" always;
    add_header Pragma "no-cache" always;
    expires -1;
}
